export default [
  {
    id: 'small_deflectors',
    name: 'Small Deflector',
    category: 'shield',
    slot: 1,
    energy: 15,
    defense: 50,
  },
  {
    id: 'medium_deflectors',
    name: 'Medium Deflector',
    category: 'shield',
    slot: 2,
    energy: 30,
    defense: 125,
  },
  {
    id: 'large_deflectors',
    name: 'Large Deflector',
    category: 'shield',
    slot: 4,
    energy: 60,
    defense: 300,
  },
  {
    id: 'small_nanocomposite_armor',
    name: 'Small Nanocomposite Armor',
    category: 'armor',
    slot: 1,
    energy: 0,
    defense: 50,
  },
  {
    id: 'medium_nanocomposite_armor',
    name: 'Medium Nanocomposite Armor',
    category: 'armor',
    slot: 2,
    energy: 0,
    defense: 125,
  },
  {
    id: 'large_nanocomposite_armor',
    name: 'Large Nanocomposite Armor',
    category: 'armor',
    slot: 4,
    energy: 0,
    defense: 300,
  },
];
