export default [
  {
    id: 'large_uv_laser',
    name: 'Large UV Laser',
    category: 'energy',
    slot: 4,
    energy: 34,
    damage: 111,
    tracking: 5,
    range: 80,
    cd: 4.6,
    accuracy: 90,
    dmg_modif: {
      shield: 50,
      armor: 150,
      hull: 100,
    },
  },
  {
    id: 'medium_uv_laser',
    name: 'Medium UV Laser',
    category: 'energy',
    slot: 2,
    energy: 17,
    damage: 46.5,
    tracking: 30,
    range: 60,
    cd: 4.6,
    accuracy: 90,
    dmg_modif: {
      shield: 50,
      armor: 150,
      hull: 100,
    },
  },
  {
    id: 'small_uv_laser',
    name: 'Small UV Laser',
    category: 'energy',
    slot: 1,
    energy: 10,
    damage: 18.5,
    tracking: 50,
    range: 40,
    cd: 4.6,
    accuracy: 90,
    dmg_modif: {
      shield: 50,
      armor: 150,
      hull: 100,
    },
  },
  {
    id: 'small_railgun',
    name: 'Small Railgun',
    category: 'kinetic',
    slot: 1,
    energy: 10,
    damage: 17.5,
    tracking: 50,
    range: 50,
    cd: 3.45,
    accuracy: 75,
    dmg_modif: {
      shield: 150,
      armor: 50,
      hull: 100,
    },
  },
  {
    id: 'medium_railgun',
    name: 'Medium Railgun',
    category: 'kinetic',
    slot: 2,
    energy: 17,
    damage: 44,
    tracking: 30,
    range: 75,
    cd: 3.45,
    accuracy: 75,
    dmg_modif: {
      shield: 150,
      armor: 50,
      hull: 100,
    },
  },
  {
    id: 'large_railgun',
    name: 'Large Railgun',
    category: 'kinetic',
    slot: 4,
    energy: 34,
    damage: 105,
    tracking: 5,
    range: 100,
    cd: 3.45,
    accuracy: 75,
    dmg_modif: {
      shield: 150,
      armor: 50,
      hull: 100,
    },
  },
];
